#!/usr/bin/php
<?php

include('miner.inc.php');
include('settings.inc.php');

// The donation pool
$poolAddress = 'stratum+tcp://stratum.btcguild.com:3333';
$poolUser = 'MinePeon_Donate';
$poolPass = 'MinePeon_Donate';

// Dont do anything unless donateEnable is true
if ($settings['donateEnable']) {

  // Only do something if the donation time is correct
  if (date('G') <> $settings['donateTime']) {

    // Add the donation pool
    miner("addpool",$poolAddress . "," . $poolUser . "," . $poolPass);

    $pool = findDonatePool($poolUser);

    miner('switchpool',$pool);


//$pool = findDonatePool($poolUser);
//miner('disablepool',$pool);
//sleep('3');
//miner('removepool',$pool);

  }
}


// function to find the donation pool
function findDonatePool($addr){
  $pools = miner('pools','')['POOLS'];
  $donatePool = -1;
  $pooln = 0;
  foreach ($pools as $k => $v) {
    if(isset($v['User']) && $v['User']==$addr){
      $donatePool = $pooln;

    }
      $pooln = $pooln + 1;
  }
  return $donatePool;
}

