#!/usr/bin/php
<?php
include ('miner.inc.php');
include ('settings.inc.php');


$hostsipaddress = str_replace("\n","",shell_exec("ifconfig eth0 | grep 'inet addr' | awk -F':' {'print $2'} | awk -F' ' {'print $1'}"));

//echo $hostsipaddress;

//echo $settings['userTimezone'];

// All api updates should start with the api key of the device

$api_update = "?apikey=" . $settings['apikey'];

// Standard fiels added the the end of all responces

$api_update .= "&hashrate=" . $settings['current_hashrate'];
$api_update .= "&ip=" . $hostsipaddress;
$api_update .= "&version=" . $version;

$api_server = "https://mineforeman.io/API/";

file_get_contents($api_server . $api_update);
