#!/usr/bin/php
<?php

require_once('miner.inc.php');
require_once('settings.inc.php');

// The donation pool
$poolAddress = 'stratum+tcp://stratum.btcguild.com:3333';
$poolUser = 'MinePeon_Donate';
$poolPass = 'MinePeon_Donate';

// Check to see if it is not the donation time
if (date('i') < $settings['donateAmount'] and date('H') == $settings['donateTime']) {
  // Valid donate time, dont find and remove the donation pool
} else {
  // Invalid donate time, find and remove the donation pool
  $pool = findPool($poolAddress, $poolUser);
  if ($pool) {
    sleep(1);
    miner('disablepool', $pool);
    sleep(1);
    $pool = findPool($poolAddress, $poolUser);
    sleep(1);
    miner('removepool', $pool);
  }
}

