#!/bin/sh

NTPDATE=`ntpdate pool.ntp.org`
READDATE=`date`

HASHRATE=`/opt/minepeon/bin/hashrate.php`
echo $HASHRATE


FILE=/opt/minepeon/var/rrd/hashrate.rrd
 
if [ -f $FILE ];
then
   echo "File $FILE exists"
   /usr/bin/rrdtool update $FILE $HASHRATE
   rrdtool graph /opt/minepeon/http/rrd/mhsav-hour.png DEF:hashrate=/opt/minepeon/var/rrd/hashrate.rrd:hashrate:AVERAGE CDEF:realspeed=hashrate,1000,* LINE2:realspeed#FF0000
else
   echo "File $FILE does not exist...  createing"
   /usr/bin/rrdtool create $FILE --step 300 DS:hashrate:GAUGE:600:0:U RRA:AVERAGE:0.5:1:288 RRA:AVERAGE:0.5:12:1680 RRA:AVERAGE:0.5:228:365
fi
